volumes:
  postgres_data: {}
  opensearch_data: {}
  caddy_data: {}
  app_cargo_data: {}
  app_build_data: {}
  app_deps_data: {}
  app_native_data: {}
  s3_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      # Use this env variable to control the logs levels from different modules.
      # The syntax is `{module.function}=level,...`. The filter evaluation stops
      # on the first `{module.function}` that has a prefix match against the log
      # event's module and function. The last entry in the list of filters should
      # be a bare `level` which will be used as a catch-all for all other log
      # events that do not match any of the previous filters.
      - PHILOMENA_LOG=${PHILOMENA_LOG-Ecto=debug,Exq=none,PhilomenaMedia.Objects=info,debug}
#      - MIX_ENV=dev
      - MIX_ENV=prod
      - FAKE_ENV=prod
      - APP_HOSTNAME=booru.plexa.dev
      - APP_IP=0.0.0.0
      - PGPASSWORD=${PGPASSWORD}
      - ANONYMOUS_NAME_SALT=${ANONYMOUS_NAME_SALT}
      - HCAPTCHA_SECRET_KEY=${HCAPTCHA_SECRET_KEY}
      - HCAPTCHA_SITE_KEY=${HCAPTCHA_SITE_KEY}
      - PASSWORD_PEPPER=${PASSWORD_PEPPER}
      - TUMBLR_API_KEY=${TUMBLR_API_KEY}
      - OTP_SECRET_KEY=${OTP_SECRET_KEY}
      - ADVERT_FILE_ROOT=adverts
      - AVATAR_FILE_ROOT=avatars
      - BADGE_FILE_ROOT=badges
      - IMAGE_FILE_ROOT=images
      - TAG_FILE_ROOT=tags
      - AVATAR_URL_ROOT=/avatars
      - ADVERT_URL_ROOT=/spns
      - IMAGE_URL_ROOT=/img
#      - IMAGE_URL_ROOT=https://boorucdn.judge.sh/images
      - BADGE_URL_ROOT=/badge-img
      - TAG_URL_ROOT=/tag-img
      - OPENSEARCH_URL=http://opensearch:9200
      - REDIS_HOST=valkey
      - DATABASE_URL=${DATABASE_URL}
      - CDN_HOST=boorucdn.plexa.dev
      - MAILER_ADDRESS=booru@plexa.dev
#      - START_ENDPOINT=true
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - SITE_DOMAINS=booru.plexa.dev
      - S3_SCHEME=https
      - S3_HOST=588bf4099b3f4afed2ac29958b07b7d3.r2.cloudflarestorage.com
      - S3_PORT=443
      - PORT=4000
      - S3_BUCKET=booru-judge-sh
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SMTP_RELAY=email-smtp.us-east-1.amazonaws.com
      - SMTP_PORT=587
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    working_dir: /srv/philomena
    tty: true
    volumes:
      - .:/srv/philomena
      - app_cargo_data:/srv/philomena/.cargo
      - app_build_data:/srv/philomena/_build
      - app_deps_data:/srv/philomena/deps
      - app_native_data:/srv/philomena/priv/native
    depends_on:
      - postgres
      - opensearch
      - valkey
#    ports:
#      - '5173:5173'

  postgres:
    image: postgres:17.7-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    attach: false

  opensearch:
    image: opensearchproject/opensearch:3.2.0
    volumes:
      - opensearch_data:/usr/share/opensearch/data
      - ./docker/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    attach: false
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  valkey:
    image: valkey/valkey:8.1.3-alpine
    attach: false

  files:
    image: andrewgaul/s3proxy:sha-9f66ef5
    environment:
      - JCLOUDS_FILESYSTEM_BASEDIR=/srv/philomena/priv/s3
      - S3PROXY_IGNORE_UNKNOWN_HEADERS=true
    volumes:
      - .:/srv/philomena
    attach: false

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/srv/philomena
      - ./docker/web/config:/etc/caddy
      - caddy_data:/data
    environment:
      - APP_DIR=/srv/philomena
      - S3_ENDPOINT=https://588bf4099b3f4afed2ac29958b07b7d3.r2.cloudflarestorage.com:443
      - S3_BUCKET=booru-judge-sh
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    attach: false
    depends_on:
      - app
#    ports:
#      - '8080:80'
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: "tunnel --no-autoupdate run"
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
